### ISSUE TITLE
Open profile when you click on "C::S"

### ISSUE THREAD

**Issue by brainscript** [code-stats/code-stats-atom#5]
![cs](https://cloud.githubusercontent.com/assets/8706734/21955239/fa1a61b0-da66-11e6-9fcb-919a0632b80e.png)

A click on the __C::S__ in the status bar should **bring up the profile of the current user**.
This could be implemented as a simple link to `https://codestats.net/users/username` or with a dialog showing the stats and would allow users to quickly open their profile without entering the URL in the browser.

**Comment by Nicd** [comment]
Good idea! I have to check how to make the status bar text a link.

**Comment by Nicd** [comment]
This issue has moved to https://gitlab.com/code-stats/code-stats-atom/issues/5
