### ISSUE TITLE
Doesn't recognize LaTeX

### ISSUE THREAD

**Issue by viktorsec** [code-stats/code-stats-atom#6]
Hey,

I'm editing some `.tex` files and the syntax highlights correctly and status bar labels the language as `LaTeX`, but codestats.net counts it toward the `Plain text` skill.

Is this an issue with the CodeStats package, or does the syntax highlighter omit to set something it should?

- macOS Yosemite
- Atom 1.16.0 x64
- `latex` 0.43.0 (Atom package - compiling)
- `language-latex` 1.0.0 (Atom package - syntax highlight)

**Comment by Nicd** [comment]
Hey, I will check this.

**Comment by Nicd** [comment]
I installed `language-latex` and created a new file `test.tex`. It reports as LaTeX in Atom's status bar and is sent as that to the service.

Are you able to reproduce this on a clean install?

**Comment by Nicd** [comment]
If you want to test without affecting your stats, please register on https://beta.codestats.net/ and set your `code-stats-atom` API URL to `https://beta.codestats.net/api/my/pulses/`. :)

**Comment by viktorsec** [comment]
I'm sorry for bothering you, it turns out the issue does not exist. The first edits after setting up the C::S api key on this computer were counted towards plain text, but the newer ones are counted correctly.

It might be a result of installing the `language-latex` highlighting *after* opening and editing part of the `.tex` file. Maybe the package had some "backlog" of edits that were made while the file was recognised as `plain text`?

Anyway it seems to be working properly now, so I suppose it was my error. I should have observed it more before creating an issue. Cheers!

**Comment by Nicd** [comment]
Yes, currently the plugin collects edits even when the API key is not set, they are sent when the key is available (it's a side effect of collecting even when there's no Internet connectivity and storing them for later sending). I suppose that is not good behaviour though, so I will add an issue to remove it at some point in the future.
